name: Deploy Portfolio

on:
  push:
    branches:
      - main  # deploy only from main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configure AWS credentials for deploy-portfolio user
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 3. Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22  # match your dev environment

      # 4. Build the React app
      - name: Install dependencies & build
        run: |
          npm ci
          npm run build

      # 5. Sync the build folder to S3
      - name: Deploy to S3
        run: |
          aws s3 sync portfolio/build/ s3://personal-website-df --delete


